name: Full Redeploy EC2

on:
  workflow_dispatch:
    inputs:
      ec2_deploy_path:
        description: 'Path on EC2 to deploy to'
        required: true
        type: string
        default: '/home/ec2-user/h360tk_philippines'
      deploy_ref:
        description: 'Git ref to deploy from'
        required: false
        type: string
        default: 'refs/heads/main'

jobs:
  call_full_redeploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable full redeploy workflow
        uses: simpledotorg/poc_heart360_on_grafana/.github/workflows/deploy-ec2-full-redeploy-reusable.yml
        with:
          ec2_deploy_path: ${{ inputs.ec2_deploy_path }}
          deploy_ref: ${{ inputs.deploy_ref }}
        secrets:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
